const hobbies = [
  "• Travelling",
  "• Watching movies that increase my IQ, lol.",
  "• Catching up with my friends",
  "• Reading inspirational books",
  "• Cooking new recipes",
  "• Hiking through nature trails",
  "• Playing chess to sharpen my mind",
  "• Exploring new restaurants",
  "• Volunteering for community projects",
  "• Learning foreign languages",
  "• Journaling my daily thoughts",
  "• Painting abstract art",
  "• Solving puzzles and brain teasers",
  "• Taking long walks to clear my mind",
  "• Listening to calming music",
  "• Watching documentaries on psychology",
  "• Practicing yoga and mindfulness",
  "• Trying out DIY crafts",
  "• Attending live concerts",
  "• Stargazing and learning constellations",
  "• Binge-watching clever TV shows",
  "• Dancing like no one’s watching",
  "• Playing the guitar (or trying to!)",
  "• Meditating for inner peace",
  "• Going on spontaneous adventures",
  "• Writing poetry in my free time",
  "• Learning coding challenges",
  "• Playing video games with complex plots",
  "• Attending open mic nights",
  "• Visiting museums and galleries",
  "• Listening to podcasts that teach me stuff",
  "• Gardening even though I forget to water plants",
  "• Watching TED Talks for fun",
  "• Taking online courses I never finish",
  "• Designing mood boards on Pinterest",
  "• Going thrift shopping with friends",
  "• Making playlists for every mood",
  "• Playing board games on weekends",
  "• Editing photos just for aesthetics",
  "• Exploring photography spots",
  "• Doing skincare like it’s a ritual",
  "• Binge-reading webcomics",
  "• Watching motivational videos (and zoning out)",
  "• Planning dream vacations",
  "• Scrolling Pinterest like it’s a job",
  "• Learning random trivia",
  "• Talking about deep life questions",
  "• Trying (and failing) to paint landscapes",
  "• Making digital art",
  "• Watching movies with mind-blowing plots",
  "• Writing short stories for fun",
];

const hobbiesContainer = document.getElementById("hobbies");
